name: Docker Exec Test
on: push

jobs:
  DockerAlpineExec:
    name: Docker Alpine Exec
    runs-on: ubuntu-latest
    steps:
      - name: docker image get
        uses: docker://alpine:3.11

      - name: docker gcloud image
        uses: docker://gcr.io/cloud-builders/gcloud
        with:
          args: version